### ISSUE TITLE
Mac OS : Extension build crash

### ISSUE THREAD

**Issue by jcommaret** [voideditor/void#104]
inside extensions/void
The command 

`npm run build`

Crash with error message : 
`✘ [ERROR] Cannot start service: Host version "0.23.1" does not match binary version "0.23.0" ` 

`npm run watch` instead is working. 

I am not able to build the extension.

**Comment by jcommaret** [comment]
fixed with 
`npm install eslint@0.23.1`

**Comment by spidy0x0** [comment]
> npm install eslint@0.23.1 --save-dev into extensions/void

this doesn't fix the issue. 
the issue is related to the ```esbuild``` library. version mismatch

rolling back to 0.23.0 fixed the issue
```bun install esbuild@0.23.0 --save-exact```
or 
```npm install esbuild@0.23.0 --save-exact```
